### ISSUE TITLE
Happy deanonymize day

### ISSUE THREAD

**Issue by milksense** [d0kur0/toster-stickers#11]
[Your sticker set](https://res.cloudinary.com/d0kur0/image/upload/c_fill,w_250/v1/elRisitas/7) where `...com/d0kur0/image...` contains your username
> [sc](https://github.com/d0kur0/toster-stickers/blob/master/src/globalStores.ts#L10)

**Comment by d0kur0** [comment]
This is a feature of cloudinary, the url is generated with my account name. Do you see this as a problem?

**Comment by w3bsme** [comment]
[3rd party issue](https://cloudinary.com/documentation/managing_assets)
